src/build.py

The waterfall used to archive the same archives under two names. Only use one name.
Also archive the latest build, regardless of success, to supplement lkgr.

Only archive under the git hash, not svn ID, and archive latest build

---

src/build.py

This is required to support: https://codereview.chromium.org/1577943002/
Eventually we'll want other repositories to also be able to trigger builds. Maybe the lastest and lkgr files should also contain all the hashes that they've checked out, not just the one from BUILDBOT_REVISION. With that the build could use lkgr to only trigger on one repository, and keep all other repositories at lkgr (so they don't all float).
The output is now json, and contains information on all the repos as well as the build number and what schedule triggered the build. The archives are now named based on build number.
The following binaryen patch teaches binaryen this new format:
WebAssembly/binaryen@9a3a2cb

Allow either clang or LLVM to trigger builds

---

src/build.py

Reverts WebAssembly/waterfall#11
Gyp isn't available it looks like. I'll investigate and fix later.
```
Traceback (most recent call last):
File "build/gyp_v8", line 35, in <module>
import gyp_environment
File "/b/build/slave/linux/build/src/src/work/v8/build/gyp_environment.py", line 13, in <module>
import vs_toolchain
File "/b/build/slave/linux/build/src/src/work/v8/build/vs_toolchain.py", line 24, in <module>
import gyp
ImportError: No module named gyp
Traceback (most recent call last):
File "/b/build/slave/linux/build/src/src/build.py", line 589, in <module>
sys.exit(main())
File "/b/build/slave/linux/build/src/src/build.py", line 566, in main
BuildV8()
File "/b/build/slave/linux/build/src/src/build.py", line 425, in BuildV8
proc.check_call(['build/gyp_v8'], cwd=V8_SRC_DIR)
File …
```

Revert "Build V8"

---

src/build.py

This makes it much easier to run the integration tests by themselves.
Also disable the V8 lint checks; they depend on depot_tools and don't
work everywhere.

Add options to skip sync and/or build stages

---

src/compile_torture_tests.py
src/execute_files.py
src/test/asm2wasm_run_known_gcc_test_failures.txt
src/testing.py

Previously the asm2wasm tests used the binaryen interpreter compiled
into wasm.js. Now we use Binaryen's native-wasm method to use V8
directly. However we still use sexpr-wasm to encode the binary, so that
Binaryen's binary format need not match V8's.

Switch the asm2wasm tests to use V8's native wasm support

---

src/build.py

sexpr-wasm won't build anymore (actually CMake won't configure) without
gtest. So we need to use at least that submodule.
So this CL adds submodule init/update suport to the sync. Instead of
using all submodules (which would also sync v8, which we don't need and
is large), pass an explicit list of submodules to init.
Also don't clobber the source directory anymore.

Add submodule support to GitCloneFetchCheckout

---

src/build.py

This looks like:
```
sync targets:
binaryen chromium-clang clang emscripten fastcomp fastcomp-clang gcc llvm
llvm-test-suite musl sexpr spec v8 waterfall
build targets:
archive binaryen emscripten fastcomp llvm musl ocaml sexpr spec v8
```

Display the list of sync and build targets in help

---

src/build.py
src/compile_torture_tests.py
src/emscripten_config_vanilla
src/test/emwasm_compile_known_gcc_test_failures.txt
src/test/emwasm_run_known_gcc_test_failures.txt

This change adds the 'vanilla' (aka wasm-backend) emscripten
configuration to the waterfall, and compiles and runs the torture tests
with it (in addition to asm2wasm).

Add emscripten vanilla configuration

---

src/build.py

It would be helpful to be able to download these files from each build. I'm using them for my own testing.

Archive emcc+wasm files

---

src/testing.py

(and hit some thread-sanitizer tests, see https://github.com/WebAssembly/binaryen/pull/348)

Set maximum cpu time to 90 seconds, as 10 seconds was too short

---

src/test/d8_known_gcc_test_failures.txt
src/test/d8_musl_known_gcc_test_failures.txt
src/test/emwasm_run_known_gcc_test_failures.txt

This seems to match what the waterfall is seeing; although I'm actually getting more new passes locally...

Update expected failures after LLVM r268679

---

src/build.py
src/test/emwasm_compile_known_gcc_test_failures.txt

Previously failures in the standalone build (without emscripten) caused
the build to be red, whereas failures with emscripten were just warnings
because the support was more experimental. This PR reverses that,
because emscripten is what we expect users to be using, and the
standalone support is experimental. We keep the standalone builds
running because in the past they have sometimes been useful for catching
issues in implmentations (wasm-shell, v8, etc) and the maintenance cost
for keeping them running has been low.
Also update current failure state of tests

Make emscripten failures real and standalone failures warnings

---

src/build.py
src/emscripten_config
src/emscripten_config_vanilla

Run the emscripten test suite with the wasm backend, using the
wasm-shell (as opposed to native wasm) for now.
Also remove the attempt to use a relative path in the emscripten config
file and instead generate one with an absolute path at install time.

Add support for running emscripten test suite

---

src/build.py

Chrome's buildbot infrastructure has a module named 'tools' which is
included in the PYTHONPATH by default and conflicts with emscripten's
own 'tools' module. The waterfall script doesn't use Chrome's 'tools',
so this change scrubs PYTHONPATH when running under buildbot.

Scrub PYTHONPATH from environment when running under buildbot

---

src/build.py

I ran in to issues getting my build set up. On further investigation it makes sense to me that we use a single consistent version of cmake across all builds, rather than having a prebuilt bin and the bin that the computer this runs on happens to have.

Make build.py use the prebuilt cmake binary for all builds which use it.

---

src/build.py

Upstream binaryen has started using 0xc features. sexpr-wasm doesn't have support for that yet, so for now waterfall will sync and build both versions of binaryen.

Binaryen 0xb support

---

src/build.py
src/compile_torture_tests.py

This test executes the code generated by 0xb s2wasm, so it should be the
0xb interpreter.

Use 0xb version of wasm-shell for standalone tests and interpret-binary for emscripten tests

---

src/build.py

Some emscripten tests use the system's cmake, which doesn't work on the
build bots. Add our prebuilt version of cmake at the start of PATH to
guarantee consistency in any subprocesses that rely on cmake.

Add prebuilt cmake to PATH

---

src/build.py

Without this change steps that throw exception are
erroneously marked as succeeding.

In the case of an exception always mark current step as failing.

---

src/build.py
src/compile_torture_tests.py

Torture tests wouldn't get the right system directory when built from
anywhere other than waterfall root, because it was calculated at import
time.

Make torture tests work from any working directory

---

src/build.py

Seems like a good idea to keep all generated files
in the same directory.  Without this this show
up as untracked files in the root.

Generate `latest` and `lkgr` files in `work`

---

src/build.py
src/test/asm2wasm_run_known_gcc_test_failures.txt

Currently if the wasm-backend build of the emscripten libs fails, the
asmjs build will not run. This PR makes them both run even if one fails.

Make asmjs/wasm builds of emscripten libs independent

---

src/build.py
src/cloud.py

Now that we have multiple builders we should probably start
grouping assets rather than putting them all in single
directly.
For now, the build number is also included in the names
of the individual tar archives.
Also, drop the (now-redundant) `git/` and `svn/` distiction.

Group archived assets under <buildername>/<buildnumber>

---

src/build.py

em_config was being used to form the output
filename but was an absolute path resulting
in strange upload paths such as:
https://storage.googleapis.com/wasm-llvm/builds/git/wasm-torture-/b/build/slave/linux/build/src/src/work/wasm-install/emscripten_config-11341.tbz2

Correct upload path for emscripten test output files

---

src/build.py

The repo is still called `sexpr-wasm-prototype` because the chromium.googlesource.com mirror has not been updated yet.

Update step and variable names for wabt rename

---

src/build.py

Throwing on unknown targets only makes sense when a list of possible
targets is given (e.g. when calling Apply), not when using bare
Check (since the filter does not necessarily contain all known targets
itself).
This refactors the actual exclusion logic into check, and implements
Apply in terms of that.

Make Filter.Check not throw on unknown targets

---

src/build.py

Notes:
1) we already import the traceback module for the build.py as a whole.
2) `traceback.print_exc()` prints out the exception, so we don't need to explicitly print it.

Print traceback when exceptions are thrown in build steps

---

src/build.py

This was accidentally introduced in #91

Fix crash in Emscripten() build function

---

src/build.py

Otherwise repeated invocations of this step will fail if the directory
isn't cleaned in between.

Remove binaryen src/js destination directory before copying

---

.travis.yml

Run a relatively quick version of build.py to check
for basic errors at CI time.

Add src/build.py to travis tests

---

src/build.py

Previously wabt didn't have an install target so we were
doing it manually.

Use 'ninja install' to install wabt tools

---

src/build.py

Previously we were only including the info for the repos
that were sync'd.   Now the info is included even with
--no-sync.
This means that the buildinfo.json file will always
contain the git hashes of the sourece that were used
to build it.

Always include repo info in summary json

---

src/testing.py

When >1,000 tests fail, calculating similarity on them takes ~3minutes on my machine.
If >50% of tests are failing, they probably have one overarching failure, and any arbitrary test case's output should be sufficient. Either that or we have bigger problems.

Skip similarity testing

---

src/build.py

emscripten is now built in two different steps.  This
change renames the first step from just `emscripten`
to `emscripten (emwasm)` for consistency with other
pairs of steps in the build.

Consitent naming of emscripten steps

---

debian/postinst
debian/prerm
debian/rules
src/build.py
src/emcc_wrapper.sh

These wrappers set/override EM_CONFIG meaning that the user's emscripten config
won't interfere with the toolchain. They also set EMCC_SKIP_SANITY_CHECK so that
emscripten won't try to write to the toolchain directory (which is not writable
in the packaged version).
Also, add /etc/alternatives for the core set of binaries in the debian package
so they are accessible via /usr/bin.
Also, fix the pyc cleanup command, and don't remove the third_party directory
(it is needed for closure-compiler.jar at least).

Create emcc/em++ wrappers in toolchain bin directory

---

debian/rules
src/build.py
src/emcc_wrapper.sh
src/emscripten_config
src/emscripten_config_vanilla

The bin directory is normally reserved for executable that
should be in the PATH, not entire subdirectoris.

Package emscripten in the root of the toolchain rather than under `bin`

---

src/assemble_files.py

Not used on the continuous build, but is useful for checking
compatibility between implementations.

Add support for Binaryen's wasm-as to assemble_files.py

---

src/build.py

The trunk LLVM install uses INSTALL_TOOLCHAIN_ONLY to avoid getting all
the static libraries, and copies a few extra tools. Use the same logic
for fastcomp, which should cut down the tarball size.

Install fastcomp without static libs

---

src/build.py
src/test/spec_known_gcc_test_failures.txt

Also update expected failures, and change failure state back to error instead of warning, as the blocking bug has been fixed.

Set spec branch back to master

---

src/build.py
src/test/asm2wasm_run_known_gcc_test_failures.txt

They now work again with 0xc. emwasm still has failures to be investigated.

Switch asm2wasm torture tests back to native-wasm mode

---

src/build.py

We're shipping asm2wasm as the officially supported toolchain for dev
preview, we'd like to make sure it's stable with V8.
- Moved ExecuteEmscriptenTestSuite closer to its usage
- asm2wasm testsuite should be an error if anything fails
This has a dependency on https://github.com/kripken/emscripten/pull/4633 , which disables the one currently known failing test.

Add the emscripten testsuite ran with asm2wasm

---

src/build.py

Also move it behind the buildbot check

Allow failure of debian package upload

---

src/build.py

The version number of the debian package is now dependent
of the build number.

Fix upload of debian package

---

src/build.py

The repo has moved to a new location.

Update git base for musl (which includes the bare test JS loader)

---

src/build.py

It's broken with LLVM_LINK_LLVM_DYLIB until
https://reviews.llvm.org/D25304 lands.

Disable llvm regression test run on Mac

---

src/test/d8_musl_known_gcc_test_failures.txt
src/test/emwasm_run_known_gcc_test_failures.txt

Musl fixes came from fixing wasm memory export in
https://github.com/jfbastien/musl/commit/e236cd08cbd8840594faf6857724db6ecc7adb49

Update known failures

---

src/build.py

The configure script's detection of cross-compilation is broken, and thinks we
are always cross-compiling, and thus can't detect the datatype sizes.
Also refactor SyncOCaml so that it appears in the list of valid sync targets.

Don't pass cc flag to OCaml configure on mac

---

src/build.py

This isn't needed for upstream LLVM since https://reviews.llvm.org/D24676 but is still needed for fastcomp until it updates to include that patch.

Copy libLLVM dylib for mac and windows too

---

src/build.py
src/emscripten_config
src/emscripten_config_vanilla

Node.js isn't part of the base image for our buildbots, so it disappears whenever they get swapped or wiped. Use a prebuilt from nodejs.org (mirrored locally) instead. Keep the config file's fallback to /usr/bin/node in case someone ends up using that config file. Also use node as the compiler engine, as that more closely reflects what users are likely to do.

Use prebuilt binary node.js

---

src/build.py

By "support" I mean bail out in all the places that don't work yet.
Without CMake, the only build that can run is V8. The rest depends
directly or indirectly on CMake, and no doubt the test runners need
work. But since something works at all, we can at least keep it from
regressing.

Add "support" for Windows

---

src/build.py
src/proc.py

Instead of using sys.executable and windows extensions explicitly, make proc handle them automatically.

Fold fixes for python scripts and windows executables into proc

---

src/test/asm2wasm_run_known_gcc_test_failures.txt

These were fixed in https://github.com/WebAssembly/binaryen/pull/821

Update asm2wasm known failures

---

src/test/asm2wasm_run_known_gcc_test_failures.txt

As suggested by @dschuff in #146.
Sadly (?) nothing interesting turned up, was hoping for another interesting bug like that float thing. But I guess it's good to know that nothing that should work is broken. In particular, no failure is wasm-specific, it all is stuff expected to fail in asm.js too:
* The `returnaddress` and `frameaddress` builtins cannot be supported in asm.js or wasm.
* Inline assembly stuff. (This is maybe the one thing we could make work, we could add some workaround to ignore them I guess, they seem like memory barriers, but that's not something we need to test yet anyhow.)
* Stuff that aborts in native clang - things that only work in gcc, weird builtins and such, or undefined behavior that clang handles differently than gcc (e.g. the first in that category is a …

Triage asm2wasm known failures

---

src/build.py

* Use the official CMake binary distribution for all platforms, including Windows
* Unify CMake download with SyncTarball, which does the same thing
* Enable WABT and Binaryen builds on Windows

Unify CMake binary sync and support Windows

---

.travis.yml
src/build.py
src/file_util.py
src/gyp.py
src/host_toolchains.py

Chrome's buildbots are special in that they do not have toolchains installed on the system. Instead they use a toolchain packaged and managed by depot_tools. This PR adds support for that setup.
* Factor toolchain stuff into host_toolchains.py
* Use scripts from Chromium's build tools repo to locate and use depot_tools toolchain
* Inject an environment like what CMake expects (similar to vcvars.bat) into build steps.

Support building CMake projects on Windows with Chromium infrastructure

---

src/host_toolchains.py

Turns out we've been fetching but not actually updating the tools/clang
directory, so we haven't been getting the clang rolls.

Fix SyncPrebuiltClang to actually pull new versions of clang

---

src/build.py

The patch fixing LLVM_LINK_LLVM_DYLIB has landed upstream

Re-enable LLVM regression tests on mac

---

src/build.py
src/host_toolchains.py

LLVM's tests require unix utilities from GNUWin32, so download a prebuilt
of that, and inject into the PATH when building and testing LLVM.
Also disable building the LLVM dylib, as that seems broken on windows
currently.

Build LLVM on windows

---

src/build.py

Our mac bot has an old XCode with an ld64 that is too old for libLTO
as built on trunk, and it's causing the tests to fail.

Disable build of libLTO in LLVM

---

src/build.py

We don't need them and it builds a lot fewer files this way.

Disable iOS builds of compiler-rt

---

src/build.py
src/host_toolchains.py

Several of clang's regression tests use some nontrivial unix utilities
and/or bash features. We've been using the gnuwin32 ports of these
utilities, but for reasons I don't fully understand yet, this
reliably causes some issues with temp files created by tests on
windows 7 (windows 10 seems fine). The git that comes with
depot_tools has an msys bash with msys versions of these utilities
that are sufficient for running the LLVM tests, so switch to that
for now.

Use git bash from depot_tools for LLVM regression tests

---

src/build.py
src/proc.py

Everywhere that we aren't actually using the output of the git command, use `proc.check_call()` instead of `proc.check_output()` so the output is shown in the build log.

Move special-casing of git from build.py to proc.py

---

src/assemble_files.py
src/build.py
src/compile_torture_tests.py
src/execute_files.py
src/link_assembly_files.py
src/testing.py

Several changes:
* Add a no_windows suppression to Test (like for Build)
* Invert the no_windows default for Build since most of the builds work now.
* Support windows in the Musl build
* Support windows in the bare test runners.

Run the bare tests on Windows

---

src/build.py

The `Tar` function shells out to the `tar` binary, which doesn't exist on Windows. Instead of reimplementing `Tar`, this PR uses a format more "native" to the platform. Also make the naming of the archiving and uploading functions more consistent.

Use zip archives instead of tar on Windows

---

src/execute_files.py

`wasm.opt` is the filename of the spec interpreter, so don't strip off
all suffixes; just ones that correspond to Windows executables

Only strip off windows exe suffixes in execute_files

---

src/build.py

* Sync the windows node.js
* Build emscripten
* Fix test running and enable asm.js and emwasm tests

Support emscripten on Windows

---

src/build.py

Binaryen debug build is pathologically slow on Windows, so use Release
Install MSVC dlls at fastcomp install time (after the dest dir exists), not separately.

Fixes for fastcomp and binaryen windows builds

---

src/test/emwasm_run_known_gcc_test_failures.txt

Update emwasm expected failures

---

.travis.yml

The WABT build uses C++11 now.

Update Travis build to use Trusty for a newer C++ compiler

---

src/assemble_files.py
src/build.py
src/compile_torture_tests.py
src/execute_files.py
src/link_assembly_files.py

Also, don't import modules except at the top level.

Use 'main' consistently for python entry point name

---

src/build.py

This mirror is now fixed and seems to be more
up-to-date than other mirrors such as github.

Switch to llvm.googlesource.com

---

src/execute_files.py

Async compilation is currently breaking the d8 tests
because its exiting before the promises resolve.
BUG=https://bugs.chromium.org/p/v8/issues/detail?id=6263

Add --no-wasm-async-compilation when running d8 tests

---

src/test/emwasm_compile_known_gcc_test_failures.txt
src/test/run_known_gcc_test_failures.txt

https://reviews.llvm.org/D32487 seems to have fixed some vector instruction compilation, and https://bugs.llvm.org//show_bug.cgi?id=26452 additionally seems resolved

Update newly-passing tests

---

src/build.py

This is partial fix for #197.  For steps that upload
more than one archive only one link is shown in the
buildbot GUI.  This change makes uploads the binaries
last in the step which fixes the link.  Really we should
give them different link names so they both appear but
that is larger change.
Secondly, remove the build number from the filenames
since it is already present in the directory name.

Fix download link for "Archive binaries" step

---

debian/postinst
debian/prerm
src/build.py
src/execute_files.py
src/test/spec_known_gcc_test_failures.txt

Upstream changed the optimised build to just 'wasm' and
the debug build to 'wasm.debug' in:
https://github.com/WebAssembly/spec/pull/475

Update name of spec interpreter wasm.opt -> wasm

---

src/host_toolchains.py

`v8\gypfiles` is deprecated and will be removed completely end of 2017. Use updated scripts in `build` folder instead.

Use up-to-date build\{vs_toolchain.py,win_toolchain.json}

---

src/test/spec_known_gcc_test_failures.txt

These all seem to be related to calls to __builtin_memset
no longer being generated in the .s files.

Remove 9 expected failures from spec_known_gcc_test_failures.txt

---

src/host_toolchains.py

#202 directly uses `<workspace>\build\vs_toolchain.py`. It assumes `<workspace>\build\..\tools\gyp\pylib` exists to `import gyp`, but `tools\gyp\pylib` is pulled by `gclient sync` and lives under `<workspace>\v8\v8` instead of under `<workspace>`.
See https://cs.chromium.org/chromium/src/build/vs_toolchain.py?type=cs&q=%22import+gyp%22&l=21
Depending on scripts in v8\build is fine since they are updated everyday.
Failure log: https://wasm-stat.us/builders/windows/builds/8788/steps/Sync%20Repos/logs/stdio/text

Use vs_toolchain.py and win_toolchain.json in v8/build 

---

src/build.py

The musl build script now supports build with with
the wasm32-unknown-unknown-target.

Build musl as wasm object files as well as .s files

---

src/build.py

For some reason the waterfall seems to dislike the wasm-no-cjit-yes-tls-context tests. They work on the JSC infra, and I'm not sure it's useful to run all tests 5-ways for the waterfall anyways. --fast will only run with the basic command-line setup, not the extra 4 variants we otherwise have.

Run jsc tests with --fast

---

src/build.py
src/buildbot.py

Currently JSC build is using cmake build, which is not the official
build, and this makes JSC build flaky. This makes JSC build failure
not stop the whole waterfall process so that we can proceed to the
test stage.

Make JSC build failure not abort the whole process

---

src/test/emwasm_compile_known_gcc_test_failures.txt
src/test/run_known_gcc_test_failures.txt

This PR will be used to update GCC test failure descriptions to track
failures we need to fix. Related to kripken/emscripten#5488.

Update GCC test failure descriptions

---

src/test/run_known_gcc_test_failures.txt

This should green the tree and allow us to remove
the warn-only settings for these tests.

Update expectations for execution of lld output

---

src/link_assembly_files.py
src/test/run_known_gcc_test_failures.txt

We pass -DSTACK_SIZE to the compiler but ommited to set the
stack size at link time.

Add -zstack-size to lld builds

---

src/test/lld_known_gcc_test_failures.txt
src/test/lld_musl_known_gcc_test_failures.txt
src/test/spec_known_gcc_test_failures.txt

This updates some of newly discovered failures as we add new
optimization levels to waterfall. Some of lld failures are marked as
'untriaged'.
Currently this only updates steps included in bare tests that are
considered as STEP_FAILURE if unexpected successes/failures occur. More
to come.

Update GCC bare test expectations for lld and spec

---

src/assemble_files.py
src/build.py
src/compile_torture_tests.py
src/link_assembly_files.py

Currently bare tests are only compiled with -O0, whereas emcc/binaryen
tests are only compiled with -O2. This makes bare tests compiled with
both -O0 and -O2, and emcc/binaryen tests with both -O0 and -O3.
(The reason for not -O2 again but -O3 is people tend to use -O3 a lot in
real use cases and test emcc with a different set of flags will increase
test coverage.)

Make waterfall test multiple optimization levels

---

src/build.py

This disables warn_only=True option for all d8 bare tests
(bare/bare-musl/lld/lld-musl), to make it easier to notice new
unexpected failures and triage them.

Disable warn_only=True for bare d8 tests

---

src/execute_files.py

The upstream bug seems to have been fixed now.

Remove --no-wasm-async-compilation d8 flag

---

src/build.py

V8 commit d9a25842d3aba82ead5e06c7fd7cb4896e6ad202 changed Date objects
to use ICU timezone data, which is read from the icudtl.dat file.

Add icudtl.dat to V8 install

---

src/build.py
src/buildbot.py

The regression test runner is currently failing on windows for obscure reasons, but the rest of the tests seem to work, so we can at least run them rather than bailing out completely.

Split LLVM regression into its own buildbot step

---

src/compile_torture_tests.py
src/test/run_known_gcc_test_failures.txt
src/test/spec_known_gcc_test_failures.txt

A stack overflow in 960521-1.c results in an infinite loop and hangs the
bots. Reducing the size used by some of the tests works around that.

Reduce torture test STACK_SIZE define

---

src/build.py
src/file_util.py

`shutil.rmtree()` does not work when there are read-only files in a
directory. This works around that problem.

Force clobbering on windows

---

src/build.py

1. Switch from a source tarball to use a release tag on the official github repo, using our standard git checkout mechanism.
2. Check out and build `ocamlbuild` which is no longer packaged with the compiler/runtime sources.

Update OCaml build to work with 4.05

---

src/file_util.py

Shell commands like `rmdir` should have `shell=True` in `subprocess`
commands. Because `proc.check_call` assumes it takes a list and here we
want a command string, we just use `subprocess.check_call` directly here
with `shell=True`.

Fix a bug in windows clobbering

---

src/proc.py

When the `cmd` argument to `proc.check_call` is a string, the code
tried to join strings with ' ', resulting strings like `r m d i r`.

Remove stray spaces in subprocess messages (NFC)

---

src/build.py

#130 added two emscripten tests (asm2wasm and emwasm) and set only
asm2wasm to `warn_only=False` because it was the officially supported
toolchain then. Then would now be a good time to delete `warn_only=True`
for emwasm too?

Delete warn_only flag from emwasm testsuite

---

src/build.py

These new targets are needed to run the JSC tests.

Add test binaries to JSC build

---

src/build.py

Also, rename cmake directly to cmake-3.4.3 to more clearly
match the upstream version.
This change is in prepration for updating the cmake version.

Write and check stamp file when syncing archives

---

src/build.py

This auto detect feature of run-tests.py was removed
upstream in:
https://chromium-review.googlesource.com/721659

Fix invocation of v8 run-tests.py

---

src/test/run_known_gcc_test_failures.txt

The test in question contains the following code
```c
int i;
for (i = ((unsigned) ~0 >> 1) - 3; i <= ((unsigned) ~0 >> 1) + 3; i++) { ... }
```
which I believe is undefined because it relies on the signed integer `i` overflowing in order to terminate, which "can never happen", so clang optimizes it to an infinite loop.

Update test failures for clang loop optimization

---

src/build.py

Prior to this change compiler-rt was not being built for
wasm at all.

Build and install libclang_rt.builtin from compiler-rt

---

src/build.py

This reverts commit 48b89c59d4c8b5959415e047984033e393c57db4.
I think we just need to clobber the bots to make it work

Revert "Temporarily disable compiler-rt (#263)"

---

src/build.py

These tests are normally run as part of the build but
it can be useful to run a build with no tests too.
Alternatively we could split out these tests into
thier own phases.

Make running of llvm/v8/spec tests optional

---

src/build.py

Otherwise the archive index is not produced.

Using llvm-ar and llvm-ranlib when building compiler-rt

---

src/build.py
src/test/run_known_gcc_test_failures.txt

wasm.js isn't correctly linking musl.wasm so the
results are currently identical to the non-musl tests.
See https://github.com/jfbastien/musl/pull/17

Remove tests that use musl.wasm

---

src/build.py
src/link_assembly_files.py
src/test/run_known_gcc_test_failures.txt

This gives us libc and compiler-rt on the link line for free
and excercises the clang driver.

Use clang driver when linking with lld

---

src/build.py

No need to auto-generate it anymore.
See: https://github.com/jfbastien/musl/pull/21

Use musl-provided wasm.syms

---

src/test/run_known_gcc_test_failures.txt

These failures were fixed by https://reviews.llvm.org/rL317707

Update expectations after llvm fix

---

src/build.py
src/wasm_standalone.cmake

This prevents CMake from using any host system headers when compiling, (this just happens to work on the linux bot but it breaks the mac bot).

Replace compiler-rt CMake flags with a CMake toolchain description file

---

src/build.py
src/emscripten_config
src/emscripten_config_vanilla

Java installed in the buildbots are too old while emscripten uses
closure compiler that requires Java SE 8.0 (version 52) or above.

 Make waterfall use prebuilt Java

---

src/build.py

Each invocation of emcc does sanity check for the current emscripten
cache directory, whose default location is `~/.emscripten_cache`. It
compares the last modification of the configuration file
(`emscripten_config` for asmjs and `emscripten_config_vanilla` for wasm)
with that of the sanity file (`emscripten_config_sanity` for asmjs and
`emscripten_config_vanilla_sanity_wasm` for wasm), and if the
configuration file was modified after the sanity file, deletes the cache
directory and rewrites the sanity file.
https://github.com/kripken/emscripten/blob/a243a941d911698a703fd4e5210a9dbc24bc4e96/tools/shared.py#L512-L533
https://github.com/kripken/emscripten/blob/a243a941d911698a703fd4e5210a9dbc24bc4e96/tools/shared.py#L578-L582
The problem is, emcc thinks the cache is invalid when
`sanity …

Sleep after writing emscripten configuration file

---

src/build.py

These should alwasy have been installed but it recently started
mattering becasue I removed bits/mman.h.
This mimics more closely what the musl Makefile does on `install`

Install arch/generic/bits/*.h from musl as well as arch/wasm32/bits/*.h

---

src/test/run_known_gcc_test_failures.txt

This reverts commit 8331bf4ca6c0054b64e1c36be72a1cad5a3e22ce.
The upstream llvm change was reverted.

Revert "Update expectations (#291)"

---

src/host_toolchains.py

It grew a new required command-line flag in
https://chromium-review.googlesource.com/768549, so give it the value 0
(which means don't disable goma).

Update invocation of host_toolchain.py on windows

---

src/link_assembly_files.py

We are about to land a change to implements visibility
in lld and without this change main could end up not being
exported (since we default to hidden in wasm clang)

Pass --entry=main when linking with lld

---

src/build.py

This version contains a fix to the Ninja generator that properly recognizes gnu-style compilers on Windows and creates response files with the correct file path escaping.

Update CMake to 3.7.2

---

src/host_toolchains.py

This dates back to when 2013 was the other option, but now only 2017 is
supported.

Remove forcing of MSVS 2015 toolchain

---

src/build.py

This is the most recent LTS (the previous version was not an LTS, so this
one is more likely to match something users might use) and it supports wasm,
which would allow us to run wasm tests on top of it, if we want to do that
in the future.

Update prebuilt node.js to 8.9.3

---

src/build.py
src/emscripten_config
src/emscripten_config_vanilla
src/execute_files.py

Proof of concept to run bare and emscripten tests in node.js.
Everything seems to work but Interestingly there seems to be unexpected successes (compared to d8) in the emscripten torture tests (both asm2wasm and emwasm)

Run emscripten tests in node.js instead of d8

---

src/build.py

We're currently failing to link any files with lld, which causes
execute_files to assert, which prevents any later tests from running.
This allows later tests to still run.

Don't assert when there are no files to execute

---

src/build.py

This fixes lld looking for libclang_rt.builtins-wasm32.a in 7.0.0, but
us building 6.0.0

Bump compiler-rt clang version to 7.0.0

---

src/test/run_known_gcc_test_failures.txt

The test fails on -O0 because the long double rt functions are not yet
implemented in wasm.js. https://reviews.llvm.org/D41522 makes
rt-supported float inlining expensive, and so causes it not to be
inlined in -O2 as well, so disable it there too.

Expect 20030914-1.c.wast.wasm to fail

---

src/build.py

The bullet and openjpg emscripten test suite tests were failing on mac
because the bots apparently don't have a system-installed CMake anymore,
and the path we were injecting wasn't correct on mac.

Fix CMake path injection for mac

---

src/build.py
src/compile_torture_tests.py
src/test/llvm_torture_exclusions
src/test/run_known_gcc_test_failures.txt
src/testing.py

The test in question has UB and is optimized into an infinite loop. On mac and
linux the python rlimit mechanism is used to kill the program after timeout, but
there's no equivalent functionality for Windows currently. So we just exclude
the test entirely (this also makes everything run faster on mac and linux since
we aren't waiting uselessly for the timeout).

Add ability to completely exclude torture tests from test pipeline

---

src/build.py

We used to have tests that tried to use musl.wasm via runtime linking, but they were
removed in #271, and I don't know when they were last actually working or useful.
By removing this we can simplify musl's build script too.

Remove musl.bc and musl.wasm

---

src/build.py
src/compile_torture_tests.py
src/libc++abi.imports
src/link_assembly_files.py
src/test/lld_known_gcc_test_failures.txt
src/test/run_known_gcc_test_failures.txt

The gcc test suite is spread over several directories.  There are also duplicate filenames across
those directories.  This means we can't just use the test basename for complication output.
I looked into re-creating the nested structure in the output tree, but in the end it was simpler
to convert the full path into single filename (essentially replacing `\` with `__`). Hopefully this
is not too ugly!

Add support for some of the C++ gcc testsuite

---

src/build.py
src/testing.py

When working on waterfall code the thread pool can sometimes
make this very hard to debug, hiding output and errors in some
cases.

Add a simple way runs tests single threaded during development

---

src/build.py
src/compile_torture_tests.py
src/execute_files.py

Also remove saving/restoring PATH in Musl() step.  This
step doesn't modify PATH

Add ability to run build.py with a limited set of torture tests

---

src/build.py

This patch adds a step that installs [jsvu](https://github.com/GoogleChromeLabs/jsvu). For now it only does so on Windows (where jsvu then installs a `chakra` binary) and Mac (where jsvu then installs a `javascriptcore` binary), but this can easily be extended in the future.
Hopefully this can replace the complex build systems for these engines and reduce the maintenance cost of this project.

Add jsvu step

---

src/build.py
src/compile_torture_tests.py

We only test the default wasm-native one.

Remove multiple binaryen configs

---

src/build.py

It's usable again after https://chromium-review.googlesource.com/c/964221/

Go back to using d8 instead of node for emscripten tests

---

src/test/lld_known_gcc_test_failures.txt

They now compile, but don't run because they require actual thread creation.

Add tls/thread_local torture tests to llc xfails

---

src/build.py
src/host_toolchains.py

* Remove forcing of `COMPILER_WORKS` in favor of using `-nostdlib++`
* Use LLVM_PATH instead of LLVM_CONFIG_PATH because the latter doesn't work on windows (something about paths)

Update libcxx/abi builds

---

src/compile_torture_tests.py

Run all .C and .c files from the g++ torture test directory, because there it
contains both (so previously we were not testing the .c files) and Windows
can't tell the difference.
Also check whether the path contains the g++ torture test directory when
deciding whether to use clang or clang++ because Windows can't tell the
difference.

Update torture test runner for windows

---

src/host_toolchains.py

This argument is not longer needed:
https://chromium-review.googlesource.com/1015860

Remove final argument from setup_toolchain.py call

---

src/test/run_known_gcc_test_failures.txt

setjmp/longjump (and exceptions) now work in emscripten
lld builds.

Update expectations after wasm-emscripten-finalize fix

---

src/test/run_known_gcc_test_failures.txt

It tests the -fwrapv flag, which ensures that signed integers wrap on
overflow instead of having UB. We do not pass the -fwrapv flag when
we build, and clang recently started exploiting the UB in a way that
breaks the test.

Add pr23047 to expected failures

---

src/build.py
src/compile_torture_tests.py
src/test/emwasm_compile_known_gcc_test_failures.txt

Also, rename the binaryen/binaryen-lld to emscripten/emscripten-lld
to more accurately reflect the meaning of these configurations.

Remove WASM=1 flag not that its the default

---

src/build.py

This is part of the move to remove s2wasm.  When we do this
we will only producing wasm binaries from the toolchain and
not wast/wat files.
wasm-shell only supports running on the .wast files (it designed
to run the spec tests).  (It you pass it wasm file it actually just
returns 1 since wasm files are all empty strings in C!)
The wasm-shell tests have been failing for a while but we have
the in warn only mode, which is another reason I don't think we
care about coverage here.

Remove wasm-shell testing of torture tests

---

src/test/spec_known_gcc_test_failures.txt

Somehow my previous commit didn't contain the correct
expectations for some spec interpreter torture test
restuls.

Update spec interpreter expectations for torture tests

---

src/build.py
src/execute_files.py
src/test/validate_known_gcc_test_failures.txt

The object files produced by llvm should be valid wasm files
so its good to test this too.

Add validate of llvm object files

---

src/test/validate_known_gcc_test_failures.txt

This miscompile was fixed in:
https://reviews.llvm.org/rL335576
Thanks Dan!

Update validations expectations after upstream llvm fix

---

src/test/run_known_gcc_test_failures.txt
src/test/spec_known_gcc_test_failures.txt

This miscompile was fixed in:
https://reviews.llvm.org/rL335576

Update expectations after upstream llvm fix

---

src/test/emwasm_compile_known_gcc_test_failures.txt

Previously the codegen failure on __builtin_return_address was
being treated as an error (erroneously).

Update expections now that LTO warnings are error in emscripten

---

src/test/emwasm_compile_known_gcc_test_failures.txt

Wasm backend has never supported __builtin_return_address; presumably the tests only worked before due to something optimizing them away.

Add 2 emwasm compile XFAILS

---

src/test/spec_known_gcc_test_failures.txt

This seems to have been caused by a clang change that
removes the call to strcmp in the final output.

Remove an XFAIL for the spec runner

---

src/host_toolchains.py

There is an upstream llvm change the broke the ocaml
build.  This change pins the chromium clang revision to
prior build.

Pin chromium clang to a previous revision

---

src/test/spec_known_gcc_test_failures.txt

Seems that the O0 build no longer depends on memset.

Remove pr30778.c from list of known spec failures

---

src/execute_files.py

Import/export of mutable globals is now the default behavior, so the
flag to enable it has been removed.
See https://github.com/WebAssembly/wabt/pull/884

Don't pass `--enable-mutable-globals` flag

---

src/test/run_known_gcc_test_failures.txt
src/test/spec_known_gcc_test_failures.txt

See: https://reviews.llvm.org/D50471

builtin-bitops-1.c is now passing due to LLVM change

---

src/test/run_known_gcc_test_failures.txt

This should only fail under fastcomp (asm2wasm).  A little embarrassed that this took 3 changes
to fix.

Try again to update the expectaions for builtin-bitops-1.c.js

---

src/test/spec_known_gcc_test_failures.txt

Looks like the O2 build stopped depending on strcmp.  I suppose
the builtin is now inlined in this case.

Update expectations for spec interpreter

---

.vpython

This is used by the new LUCI build infrastructure. Add the win32 module which is
needed by v8gen.py

Add .vpython file

---

src/build.py

Use Executable suffix for wasm-validate

---

src/build.py
src/emscripten_config

The way embuilder builds the native optimizer with cmake doesn't work on the waterfall on Windows; and in any case it's better to force the optimizer binary anyway, to avoid building it on-demand.

Build the native asmjs optimizer in a separate step

---

src/build.py

Experimental fix to bring up the mac LUCI bot

Use gclient-managed hermetic mac toolchain on mac bots

---

src/build.py

1. Setting the env var was incorrect, use a string
2. Use the hermetic toolchain on non-bots too, for consistency (this also works
around the current problem that IsBuildbot() returns false on LUCI bots)
3. Print the current developer dir during V8 build, to enable debugging.

Fix use of hermetic mac toolchain

---

src/build.py

Reverts 45f1873, b5decd7, and 1aadd7d
Bots aren't currently set up to authenticate and download the
hermetic toolchain, and LUCI builders apparently do it differently anyway.

Remove use of mac hermetic toolchain

---

src/build.py
src/execute_files.py

The LUCI mac bots can't build d8 currently. For now,
use one installed by JSVU instead.

Use JSVU-installed d8 on mac instead of building it

---

src/host_toolchains.py

LLD needs this dll, but it isn't copied by Chromium's script.

Copy concrt140.dll along with the rest of the VS runtime

---

src/build.py
src/test/run_known_gcc_test_failures.txt

Same as #411 but pass the optlevel as an attribute to allow distinguishing between optlevels in the exclusion file.

Add Windows XFAIL and optlevel attribute during torture run

---

src/test/spec_known_gcc_test_failures.txt

Since the default for lld changed to --no-export-dynamic we
not longer export -fvisibility=default symbols.  These two
tests started passing because in the O2 case the operator new
is no longer included in the link.
It seems that operator new always visibility=default so is one
of the few symbols used in the torture tests that is effected.

Remove two known failures from spec_known_gcc_test_failures.txt

---

src/testing.py

Mac bot builds currently always fail with EAGAIN on stdout.write calls on line
247 below. One possible explanation might be a full buffer somewhere underneath,
so try flushing stdout after joining the pool and before trying to write
anything else.

Flush stdout after multiprocessing pool join

---

src/build.py

BUILDBOT_BUILDNUMBER isn't set in LUCI builds.

Make experimental mac bot fix unconditional

---

src/build.py
src/buildbot.py

When we fully switch to LUCI with recipes we can just change the
implementation.

Refactor all buildbot-related code into buildbot.py

---

src/test/run_known_gcc_test_failures.txt

I seems that references to this symbol are not longer present
in clangs -O2, so these tests now pass.

Remove expected failures due to __builtin_constant_p

---

src/test/run_known_gcc_test_failures.txt

These are still present in asm2wasm path.

Third attempt to remove expected failures due to __builtin_constant_p

---

src/build.py
src/host_toolchains.py

Introduces `CMakeCommand()`, which assembles all the common parts of a
CMake command, including the specification of the python
location. This adds the result of `OverrideCMakeCompiler()` and
`host_toolchains.CMakeLauncherFlags()` to CMake commands that did not
already have them, but hopefully that doesn't break anything.

Explicitly tell CMake python's location

---

src/test/run_known_gcc_test_failures.txt

For opt__pr15551.C it looks like the call to operator new is no
longer elided.

Update test expectations

---

src/host_toolchains.py
src/proc.py

Appending exe/bat suffixes only makes sense when we are looking for a real
executable instead of a script. Despite this fact depot_tools apparently now
includes gsutil.py.bat which turned the previous nonsensical-but-harmless
behavior into broken behavior.

When using proc.Which to find a python script on windows, don't append suffixes

---

src/testing.py

In case they are different inside the multiprocessing worker.

Print fcntl flags on each tester preexec

---

src/testing.py

Reverts WebAssembly/waterfall#437

Revert "Print fcntl flags on each tester preexec"

---

src/parallel_runner.py
src/proc.py
src/testing.py

This avoids printing to stdout from the subprocesses, in hopes of working around the EAGAIN errors on mac.

Replace multiprocessing pool with custom parallel test runner in testing.py

---

src/test/run_known_gcc_test_failures.txt

It used to fail when any optimization flag was on and the reason was
RegStackify's stack pointer store check was incorrect. This test is now
passing after the LLVM fix (https://reviews.llvm.org/rL350906).
In detail: In `check_fa_mid`, the original code order was
```
...
i32.call  check_fa_work@FUNCTION
global.set  __stack_pointer@GLOBAL
...
```
But the previous code incorrectly reordered the call to `check_fa_work`
after `global.set` while stackifying registers. `check_fa_work` has
`global.get  __stack_pointer@GLOBAL` instruction itself, resulting in
loading an incorrect value.

Remove frame-address.c from expected failures

---

src/build.py

The bot is currently timing out, so rather than increasing the timeout,
reduce the test matrix

Reduce nunber of tests on the mac bot

---

luci-scheduler.cfg

4 is the current number of allocated bots on Linux, but keep it
uniform.

Set max concurrent triggering invocations to 4

---

src/build.py

Also stops testing llvm bitcode files on all the emscripten test suite, like emscripten CI now does (testing focuses on wasm object files, with `other` covering some interesting llvm bitcode linking cases - will be improved as we improve LTO).

Update emscripten test mode names after wasm-object-files-by-default landed

---

src/test/lld_known_gcc_test_failures.txt

As of https://reviews.llvm.org/D57909 lld will no longer
generate invalid modules when function signatures mistmatch.
Instead is tries to figure out the actual functions signature.
In this case it fails to do so because the disagreement is between
two imports and there is no actual definition of `abort`.

Update expectations after llvm upstream change.

---

src/testing.py

This was disabled in #440 but it looks like was only intendted to
effect mac.
Certainly this is useful information that we generally do not want
to miss.

Re-enable logging of command to stdout (at least on non-mac)

---

src/test/run_known_gcc_test_failures.txt

The way in which signature mismatches are handled changed
in https://reviews.llvm.org/D57909.

Update expectations after lld change

---

src/build.py

It looks like the cmake change here requires a clobber build.

Trigger clobber build after 5a6060f

---

src/test/run_known_gcc_test_failures.txt

This appears to be due to d8 differences on windows that we don't quite understand,
https://bugs.chromium.org/p/v8/issues/detail?id=8211
So just update the expectations to get the windows bot green.

Update windows torture expectations

---

src/test/run_known_gcc_test_failures.txt

Which seemed to start working recently, but is now failing again, likely for the same unknown https://bugs.chromium.org/p/v8/issues/detail?id=8211 reason in the comment right above it
This reverts part of the overly-optimistic #460 
Will hopefully get the windows waterfall green.

Ignore a torture test on windows

---

src/build.py

The flakiness seems to have gotten worse this week - we've updated the expectations a few times, but really this seems like true flakiness - the same test (not one we've marked earlier this week) started to fail randomly, and we've flickered between red and green builds because of it.
In practice, running the torture tests on one platform is basically enough to test toolchain codegen, and what we were testing on windows was more affected by d8 than anything else.

Avoid running d8 tests on windows because of flakiness.

---

src/build.py

It seems that when a unittest target is removed of renamed the old
binary sticks around and continues to get run during 'check-all'.
This recent change to LLVM is all the builder to fail trying to run
the old test (OptRemarksTests): https://reviews.llvm.org/D58535

Clobber build after llvm change

---

src/build.py

We are seeing consistent errors on the bots:
`ls: write error: Resource temporarily unavailable`
Seems like it must be a chrome infra issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=940663

Disable printing off archive contents on linux as well as mac

---

src/build.py

This may work around odd hangs on the bots.

Run emscripten test suite in single core mode on MacOS

---

src/build.py

The bots are now upgraded to xenial bots so this should no longer be
needed.
See https://bugs.chromium.org/p/chromium/issues/detail?id=939830
Fixes: #467

Remove -DLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN cmake argument

---

src/build.py

Revert #470 - running emscripten tests on single core does not prevent the mac bot from hanging. Instead, just skip them for now.

Skip emscripten test suite on mac bot

---

src/build.py

This is no longer needed after: https://reviews.llvm.org/D58333

Remove -DLLVM_COMPILER_CHECKED=ON from libcxxabi build

---

.travis.yml
src/build.py
src/host_toolchains.py

Replace the git-checkout portion with a standard source rule.
This will allow replacing that with a DEPS sync.

Split host clang step into separate steps for sync and update

---

src/build.py

Prebuilt host tools (clang, CMake) are logically more like sources
than build artifacts, but put them in the build dir anyway because
on LUCI builders, the src dir will be managed by gclient, backed
by git cache, and cleared on each build (whereas the build dir
can be persisted on the builder for incremental compiles)

Use Build dir instead of Sync dir for prebuilts

---

src/build.py

This nesting isn't supported by DEPS files.

Don't nest fastcomp clang source inside LLVM checkout

---

src/build.py

My local tests still aren't working, but at least this gets rid of the unknown section errors in the torture tests.

Enable bulk-memory when validating objects

---

src/build.py
src/work_dirs.py

This has the effect of making relative paths behave uniformly and easier
to track in bot logs.
Also print the extraction directory for prebuilt archives.

Make work_dirs paths absolute

---

src/build.py

This is an attempt fix the issue we are seeing the bots with make
is error'ing out with `make: write error: stdout`

Run make with --output-sync

---

src/build.py
src/work_dirs.py

This allows V8 to be managed separately by the same gclient that checks out
emscripten-releases and be in a parallel directory (separate from the other
sources).

Add directory override for V8

---

src/build.py

Try a different method of `--output-sync=line`

Revert "Trial removal of parallelism from wasi sysroot build (#502)"

---

src/build.py

We no longer use them to test binaryen on CI, and in any case they are
easy and fast to reproduce locally.

Don't upload the torture test results

---

.travis.yml
src/build.py
src/host_toolchains.py

Currently we have our own checkout of chrome's build repo (to get the
host clang and the windows SDK) but use V8's checkout to actually
configure it because of a quirk in the directory paths they assume.
This switches to using V8's version consistently.
This has the advantage that we don't need to manage our own checkout
or DEPS entry and don't duplicate V8 logic.

Use V8's checkout of the chrome build repo instead of managing our own

---

src/build.py

It is broken and we're more interested to focus on getting other tests passing on windows.

Don't run wasi on windows

---

src/buildbot.py

We will use the revision in the storage path rathe than the build number.
Also currenly these bots don't get a valid build number, but they don't need
one.

Use revision instead as the build number for emscripten-releases bot

---

src/host_toolchains.py

Otherwise you end up with a file called 'bin' with the contents of the last dll copied.

When copying MSVCRT dlls, ensure the destination is an existing directory

---

src/build.py

Currently non-uploading bots short-circuit the upload in cloud.py.
This PR adds a first check in ArchiveBinaries, which avoids taking
the time to even create the archive if we aren't going to upload it.

Skip creation of tar file if not an uploading bot

---

src/build.py

It was disabled because it was hanging on the waterfall bot, but that
bot is broken right now anyway.

Enable upstream emscripten test suite on mac.

---

src/build.py

This is to debug why clobbers always happen on emscripten-releases.

Print reason for clobbering build

---

.vpython

This will cause the module to be available when run on Chromium infrastructure. It's used to fetch URLs on bots where the OpenSSL version is too old to use TLS1.2

Add requests module to vpython environment

---

src/build.py

They are unneeded and statically linked so each is over 20MB.

Don't bundle the largest unnecessary clang binaries

---

src/cloud.py

The storage buckets moved from per-object to per-bucket ACLs.

Remove ACL setting on gsutil uploads

---

src/build.py

Just to reduce the test matrix, as we don't expect major mac differences
and the important cases are still covered by the wasm backend emscripten
tests.

Don't run asm2wasm emscripten tests on mac

---

src/build.py

This may prevent nice colors in the output, but I didn't see that in my local testing (there's no error checking for those flags, though, so not sure I did it right).
Fixes https://github.com/emscripten-core/emsdk/issues/252

Don't link libtinfo

---

src/build.py

We removed it from LLVM, but forgot that fastcomp is built separately. This removes it there too.
Meanwhile I also verified that the LLVM build works fine, no change to colors in errors, so this seems ok to do.

Disable libtinfo on fastcomp as well

---

src/build.py

As not having it removes colors on some systems. Oddly on one machine I didn't see this, but testing on another, I do - all the colors are gone.
The eventual solution may be to statically link libtinfo. Meanwhile with it we get errors on some linuxes but proper colors, and without it we avoid linux errors but have no colors. With this PR at least the loss of colors is just on linux.
See
https://github.com/emscripten-core/emsdk/issues/252
https://github.com/WebAssembly/waterfall/pull/539
https://github.com/WebAssembly/waterfall/pull/540

Avoid libtinfo specifically on linux, where we are seeing issues

---

src/build.py

The first experiment of packaging `libc` appears to have worked - I verified emscripten github CI no longer builds libc.a, and tests look good there. Adding two more important files here,
* generated_struct_info.json is generated in a boostrapping operation that is confusing to debug if the user has a broken setup.
* optimizer.2.exe takes a while to build and also requires a local compiler environment for native executables.

Package generated_struct_info.json and optimizer.2.exe

---

src/build.py

I verified that at least locally for me, without this that executable is built with no optimizations.

Build asm.js optimizer in release mode

---

src/build.py

The asm.js optimizer is built in a special way on the bots, it turns out, and so copying it is special as well (apparently from the comment, building it normally doesn't work... and indeed when I tried to do so it failed).

Fix packaging of the asm.js optimizer

---

src/build.py

This allows more granularity on the command line (e.g. separate bot steps for each test suite, and easier to run just a single test locally).

Add comand-line paramater for selecting emscripten tests

---

src/test/emwasm_compile_known_gcc_test_failures.txt

pr56982.c started to pass after https://github.com/llvm/llvm-project/commit/b88ebe8cc9a8585647fdbff14b92841582be50a9.

Update emwasm expectations

---

src/build.py

After https://github.com/llvm/llvm-project/commit/2e97d2aa1bd313350e76be64299f19172a346bf9,
`CLANG_LINK_CLANG_DYLIB` is `ON` whenever `LLVM_LINK_LLVM_DYLIB` is
`ON`. This requires `libclang_shared.so` to be installed in
`wasm-install/lib`, but `-DLLVM_INSTALL_TOOLCHAIN_ONLY=ON` currently
disables its installation. This adds `libclang_shared.so` to `extra_lib`
so it can be installed. This fixes the current emscripten build step
failure in the waterfall.

Install libclang_shared.so* into wasm-install/lib

---

src/build.py

Previously #552 failed to install *.dylib for mac. (This tries to install the
nonexistent *.dll too just in case we enable DYLIB in Windows too, but if the
file doesn't exist, it's ok)

Install libclang_shared.dylib for mac

---

src/build.py

https://github.com/llvm/llvm-project/commit/76b26550e9b91b1b23bfe5ae40f458b69ce6b7c1
renames `libclang_shared` to `libclang-cpp`. Fixes the current waterfall
emscripten build failure. This is probably something we have to fix in the LLVM
upstream, but this makes the waterfall running in the meantime.

Rename libclang_shared.so to libclang-cpp.so

---

src/build.py

libclang is now split into multiple libraries (so we need both libclang_shared and libclang-cpp)

Copy all LLVM and clang dylibs

---

src/build.py

The bug that necessary shared libraries were not copied when
`LLVM_INSTALL_TOOLCHAIN_ONLY=ON` and `DYLIB=ON` has been fixed upstream:
https://github.com/llvm/llvm-project/commit/a196469e67ce578df4fc9f348cc5b7221f12b239
https://github.com/llvm/llvm-project/commit/1d062dae158c5ba7d1f27010d5e4178e10820ee2
So we don't need to copy them anymore.

Don't copy extra libraries anymore

---

src/build.py

This should work again with the new bot infrastructure.
Also remove redundant check in subroutine, which makes things
easier to test locally.

Restore printing of archive contents before upload

---

src/build.py

Remove a few extra binaries and libclang, and use the Executable()
utility function so that things work on Windows too.

 Further reduce the extra binaries and libs in the uploaded packages

---

src/build.py

This reverts commit 864a7e382cb9a89ed38e5f4b3fd66e2cb5952ef7.
We'd like to land this but unfortunately emscripten depends on the
host being the default for testing purposes.

Revert "Set default target triple to wasm32-wasi (#563)"

---

src/build.py

This value was being cached by the cmake build so even after reverting
the change the bot were still getting the same failures.

Clobber build after recent LLVM_DEFAULT_TARGET_TRIPLE changes

---

src/build.py

This reduces the number of tests run on the wasm-stat.us waterfall, removing
fastcomp torture tests (which are not worth keeping) and all emscripten
test-suite tests (which we run more comprehensively elsewhere).

Run a limited set of default builds/tests when invoking build.py without filters

---

src/build.py

This was removed completely in:
https://chromium-review.googlesource.com/c/v8/v8/+/1844771

Remove natives_blob.bin from v8 build

---

src/test/run_known_gcc_test_failures.txt

We don't run sanitizers on them, so all sanitizer tests (ubsan, asan,
tsan, ...) may start to fail at any point, and we shouldn't care about
the results. For now I update the expectation to match the current
behavior, but if this happens frequently enough, we may need to fix the
runner script so that we can skip those tests or something.
The two asan tests started to fail after CraneStation/wasi-libc#112, just for
reference.

Update expectations on failing asan tests

---

src/build.py

Useful for debugging bots with try jobs, and possibly for use on emscripten-releases in the future.

Add flag to manually force a clobber of work dirs before build

---

src/build.py

This will allow splitting into separate build steps on recipes-based bots.

Split LLVM Regression tests into a separate step from the LLVM build

---

src/build.py

More specifically, instead of building libs for both variants, the step
now only builds libs for the specfied variant. This allows the
llvm-test-suite bot to skip building fastcomp altogether.

Split Emscripten build step into upstream and fastcomp variants

---

src/build.py

These are regular host build targets which are required for running the LLVM
regression tests (make check) but which do not build by default from the 'all'
target. An extra build rule is used (instead of bundling it with the test
running) because the emscripten-releases shuts down goma before running
tests.

Add build target for LLVM test dependencies

---

src/build.py

CMake 3.15 has much nicer support for clang-cl on Windows.

Update to use CMake 3.15 on the waterfall

---

src/build.py

Git's usual FindPackage logic doesn't find it on LUCI (and git's now required
for wabt)

Add Git executable to CMake command line on Windows

---

src/build.py

We previously ignored errors here due to a infra bug which caused
make the retrun non-zero.  This bug appears to now be fixed:
https://crbug.com/940663

Error out if wasi-libc fails to build

---

src/build.py

We still use the MSVC SDK from V8, but now we use V8's (separately-DEPSed)
clang on Windows (the same one that we use on the other platforms).

Compile the host binaries with Clang on Windows

---

src/build.py

Chromuim's wabt mirror is stuck and out of date, so we can't roll in the
change that makes the wabt build compatible with windows clang.
So for now, fall back to MSVC

Unforce the host clang toolchain for wabt

---

src/build.py
src/test/llvmtest_known_failures.txt

For now, just the `SingleSource` tests (approximately 300 tests).
There are some current failures, which are listed in the expected_fails file, using the same format as the torture test expectations file.

Build and run the LLVM test suite

---

src/build.py

This can be done now that we've rolled the new wabt CMake files.

Build wabt with clang on Windows

---

.vpython3

It goes along side .vpython file to isolate the python environment on
Chromium builders

Add .vpython3 file

---

src/build.py

This runs v8's python scripts (which need python2) in a separate environment (controlled by v8's `.vpython` file) from the calling environment (which is python3).

Run v8 build using vpython

---

src/build.py
src/host_toolchains.py

Add .bat if necessary and also update the windows-specific logic
in host_toolchains.py

Make vpython-invocation code work on windows

---

src/build.py

Also allows use of goma. It works with
revision b4837f88af2d240abb550c0bbd47f3b8ffe5985a

Use host clang to build fastcomp

---

src/build.py
src/host_toolchains.py

Also remove the duplication of the goma-finding logic in V8,
and simplify CMake command generation now that we don't have
special-cases overriding host clang per-callsite.

Use the right number of ninja jobs for goma when building fastcomp

---

src/build.py

This overrides the default locale to always use UTF-8 for decoding text
files (on Windows the default is mbcs/cp1252). This is because our test
files are all encoded with UTF-8.

Force Python UTF-8 mode when running tests

---

src/build.py

I guess the llvm google mirror must have updated the name of this repo.

Fix git URL for llvm-test-suite

---

src/test/run_known_gcc_test_failures.txt

This llvm change make these two tests start failing in O2 and O3
where-as before they were only failing in O0:
https://reviews.llvm.org/D61314

Update expectaions after llvm change

---

src/build.py

The directory within the cache was renamed in emscripten to just "wasm".

Update emscripten cache directory

---

.github/workflows/build.yml
src/build.py
src/host_toolchains.py

This uses a hermetic build environment that will have broader
compatibility than whatever happens to be on the buildbots.
Also disable libxml2 in the LLVM build; for some reason CMake has trouble finding
it in the sysroot, but it's only needed for generating Windows manifests which we 
don't need.

Build Linux binaries in V8's sysroot

---

src/build.py

This prevents any dependence on new symbol versions in the dylib.

Link libstdc++ statically

---

src/build.py

This reverts commit e958c36835f8c91c0bee30bba32ec4448e27727a.
The test suite currently runs in the installed copy and it needs all the tests in order to run. Before relanding, we'll either run the test suite from the checkout instead, or further decouple the
test runner from the rest of emscripten.

Revert "Use emscripten's install.py to copy emscripten (#631)"

---

.flake8
.style.yapf
src/build.py
src/buildbot.py
src/cloud.py
src/compile_torture_tests.py
src/execute_files.py
src/file_util.py
src/host_toolchains.py
src/link_assembly_files.py
src/parallel_runner.py
src/proc.py
src/testing.py
src/work_dirs.py

First attempt was in #617.
Again I used yapf as a base for this change, with the following manual
tweaks:
1. Manually reflow long comment lines
2. Manually indent multi-line doc strings
3. Revert some of the argparse.add_argument changes that split args onto one per line
4. Overwride yapf for certain cases that involve nestsed function
calls.  e.g.
For example yaml seem to want to turn this:
```
proc.check_call(SetupToolchain() +
['foo', paths['win_sdk'], runtime_dirs, 'win', 'x64',
'environment.x64'],
cwd=outdir)
```
This:
```
proc.check_call(SetupToolchain() + [
'foo', paths['win_sdk'], runtime_dirs, 'win', 'x64', 'environment.x64'
],
cwd=outdir)
```
Choosing to go back out to column zero here in the middle of the
indented arguement list seems objectively wrong.

Second attempt to convert python to 4-wide indentation

---

src/build.py

The total size of the cached libraries is 33Mb and 21Mb (uncompressed)
for wasm and fastcomp respectively so I don't think its worth being
selective here.  We should probably look at shipping LTO and PIC libs
too, although maybe we should wait until we ditch fastcomp.

Include all libraries in pre-built form

---

src/build.py

Now that emscripten uses an in-tree cache just ship it in place.
This also means the emsdk doesn't have to copy any of this during
post-install.

Ship emscripten library cache in-place

---

src/build.py

The bots don't have the proper environment vars that are needed.

Inject EMTEST_LACKS_NATIVE_CLANG into env for emscripten tests on bots

---

src/build.py

Without this tags that get moved will cause the fetch to fail
with `(would clobber existing tag)`

Add --force to git fetch

---

src/build.py

This version has V8 v7.8, and in particular includes support for the wasm
fence instruction.

Update to Node LTS 12.18.1

---

src/build.py

We recently started depending more on the result on `npm ci` because
we now get acorn compiler via npm.

Run `npm ci` before trying to use emscripten

---

src/emscripten_config_fastcomp
src/emscripten_config_upstream

These files are not used by the emsdk but only internally
when testing the resulting SDK.

Cleanup emscripten config files

---

cr-buildbucket.cfg

Bug: 1109276
Change-Id: I1d0d70d6680d0252c72700a4a03fc4c309eda63a

Switch builders to use builder_group property instead of mastername.

---

src/build.py

This should allow the bundle to be used directly without running
`npm install` or `npm ci` as post-install step.

Include node_modules in uploaded bundle

---

src/build.py
src/create_sysroot.sh

This reverts commit b3c1fc5ade7dcfb495ad285e1374f6500b931513.
Turns own the resulting libm.so dependency is too recent
even to run out our own bots:
```
subprocess.check_call(`/b/s/w/ir/cache/vpython/75e09f/bin/python /b/s/w/ir/k/install/emscripten/embuilder.py build SYSTEM`, cwd=`/b/s/w/ir/cache/builder/emscripten-releases/waterfall/src`)
/b/s/w/ir/k/install/bin/clang: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /b/s/w/ir/k/install/bin/../lib/libLLVM-12git.so)
embuilder: error: '/b/s/w/ir/k/install/bin/clang --version' failed (1)
```

Revert "Switch sysroot to ubuntu bionic (#675)"

---

src/build.py

The upstream default was changed in https://reviews.llvm.org/D93177
which effectively broke our build by making the llvm binaries
non-portable.

Fix rpath in llvm build

---

src/build.py

This enables ThinLTO for LLVM and Binaryen and disables assertions on LLVM. It's off by default.

Add a build.py flag to build with extra optimizations

---

src/build.py

LLD isn't fully baked on mac yet, and the prebuilt clang
doesn't include libLTO. But the tools included with the
default SDK seem to work.

Disable prebuilt clang and LLD when building with LTO on mac

---

src/build.py

Reducing the number of link steps significantly reduces build time, and many of the built targets are not installed or used.
This uses the `LLVM_DISTRIBUTION_COMPONENTS` mechanism as documented in the [distribution guide](https://llvm.org/docs/BuildingADistribution.html).

Limit which LLVM tools are built in release/LTO mode

---

src/build.py

Also clobber before and after LTO builds.
This is accomplished by hooking into the `Run` method that runs all build rules. 
Because of that, I also moved the specification of which directory is the build directory out of the body of each build function (so the build runner could access it)

Clobber the work dir of incremental builds on failure

---

src/build.py

Individual build rules create their own subdirs, but the clobber phase was removing the top-level build dir before trying to create a file inside it.

Ensure top-level work dir/build dir exists when clobbering

---

src/build.py

This bloats the tool install size by about 30MB but also improves
speed by about 17% (using the totally-scientific metric of timing
check.py on my desktop)

Build Binaryen with static libs when using LTO

---

src/build.py

These are all the headers in lib/clang/<version> and are necessary.
Also remove unneeded symlinks/copies of lld in the install package.

Include clang-resource-headers in the install targets for the LTO build

---

src/build.py

emsdk doesn't need to support linking programs against its libbinaryen.

Build binaryen with tools only

---

src/build.py

Add a new mode to "automatically" build with LTO.
Specifically when the most recent commit in emscripten-releases modifies the
emscripten-version.txt file, build with LTO.
The use-lto flag can be set to "auto" for this behavior, or true or false.

Build with LTO automatically

---

src/build.py

Currently LTO builds are only triggered when the most recent commit modifies
the version file. But on try jobs, the files changed by the CL are not
committed; they are just modified in the index. So this change causes
LTO builds to also be triggered when the version file is modified
according to 'git status'.

Trigger LTO builds on locally-modified version file

---

src/build.py

Without this, the 'npm install' step installs a *second* copy
of the native google-closure-compiler-{os} package (as a dependency inside
the google-closure-compiler directory) in addition to the one installed
at the top level by the primary command.

Suppress optional dependencies when installing native closure compiler

---

src/host_toolchains.py

When using Chrome's hermetic toolchain, we also use a build infra utility to
set up the environment variables that VS-compatible toolchains expect.
Until recently one of the arguments to that script was irrelevant for us,
but it recently became required (now the first argument points to the
root of the toolchain package, and the 2nd sdk_path must be a subdir).

Pass correct SDK path to build's setup_toolchain utility

---

src/build.py

Instead of using emscripten-version.txt, trigger LTO builds on changes to a
separate DEPS file, DEPS.tagged-release. This change copies that over the
existing DEPS file and reruns 'gclient sync' before building. This avoids the
problem of unrelated DEPS changes racing with release DEPS changes.

Use a separate DEPS file to drive LTO/release builds
