.travis.yml
setup.cfg
src/proc.py

flake8 runs pep8 as well as pyflakes.

Use flake8 instead of pep8

---

src/build.py

This is required to support: https://codereview.chromium.org/1577943002/
Eventually we'll want other repositories to also be able to trigger builds. Maybe the lastest and lkgr files should also contain all the hashes that they've checked out, not just the one from BUILDBOT_REVISION. With that the build could use lkgr to only trigger on one repository, and keep all other repositories at lkgr (so they don't all float).

Allow either clang or LLVM to trigger builds

---

src/build.py

Reverts WebAssembly/waterfall#6
I need to update binaryen first.

Revert "Allow either clang or LLVM to trigger builds"

---

src/build.py

This was reverted in #12, try again but this time gclient sync V8.

Build and archive V8

---

src/execute_files.py

I'll need to change binaryen's binaryen-shell to support the -o option.

Add utility to execute programs.

---

src/testing.py

Because I may or may not have written an infinite loop into LLVM at some
point in my development...

Limit testing commands to 10 CPU seconds.

---

src/build.py

Checkout origin/* instead of fast-forward

---

src/build.py

https://github.com/WebAssembly/spec/issues/248 is causing the waterfall to fail. Work around the issue.

Work around spec issue

---

src/build.py

Will also convert the build rules to use it in another commit.

Augment --no-sync with a more generic filter mechanism

---

src/build.py

Work around https://github.com/WebAssembly/sexpr-wasm-prototype/issues/35 because it makes the waterfall sad.

Work around sexpr-wasm dirty repo

---

src/compile_torture_tests.py

This is minor, but at least the travis build will be happy when running flake8

Make flake8 happy by not exceeding 80 chars

---

src/build.py

This allows skipping the asm2wasm tests but running the LLVM tests

Use a Filter for tests as well as src/builds

---

src/build.py

Use it instead of the system-installed cmake, which is now too old to
build LLVM.

Download and use the CMake used to build chromium clang

---

src/build.py

This is to support https://github.com/WebAssembly/waterfall/issues/51

Add compiler-rt repo and build sanitizers for the host LLVM

---

src/compile_torture_tests.py

Emscripten's default behavior when generating .js files with wasm is now
to use wasm-as to encode a binary (previously it generated a wast
file). Since the binary 11 format, the various tools and engines have
had good agreement on the binary format and have synchronized fairly
well, so it should be safe to do this. When the format changes again we
can switch back to the previous behavior if necessary.

Use Binaryen's wasm-as to encode wasm binaries instead of sexpr-wasm

---

src/build.py

Now that LLVM requires a recent CMake, this is easy to do.

Use ccache if present for building LLVM

---

src/build.py
src/execute_files.py

Should be landed in sync with https://github.com/WebAssembly/binaryen/pull/632

binaryen-shell has been renamed wasm-shell in binaryen

---

src/build.py

v8 and the waterfall repo itself are special snowflakes.

Fix waterfall remote setup for v8 and waterfall

---

src/test/asm2wasm_run_known_gcc_test_failures.txt
src/test/d8_known_gcc_test_failures.txt
src/test/d8_musl_known_gcc_test_failures.txt
src/test/emwasm_run_known_gcc_test_failures.txt

Support for setjmp and fixes for PR29127

Update torture test expectations for LLVM r280302

---

src/build.py

Also copy the rest of Binaryen's JS files

Don't copy 0xb wasm.js-post.js over master in the binaryen install

---

src/build.py
src/find_svn_rev.py

Adding find svn rev script to avoid requiring git svn.

---

src/build.py

We don't use gyp anywhere anymore.

Don't set GYP_GENERATORS environment variable

---

src/build.py

Also, add -v so the full command lines are recorded.

Add -j50 to v8 ninja build when using goma

---

src/build.py

Needed if we want to keep the shallow clone shallow.

Set fetch depth as well as clone depth for torture test suite

---

src/build.py

* Add a Test class to mirror Build and Sync steps, unify filtering logic
* Add tests to --help message
* Add more details to error messages when sync/build/testing a nonexistent step

Test running refactoring

---

src/build.py

This is what I should have done in #97

Use CopyTree instead of shutil.copytree

---

src/build.py

Fixes name clobbering introduced in #96 , restores better names from #91

Fix test name clobbering

---

src/build.py

Until the mirror is online anyway.

Switch to github rather than mirror for `wabt` repo

---

src/build.py

WIP - tests don't pass for me locally yet, and we want to wait for wabt's 0xc branch to land.
This reverts the temporary 0xb from the waterfall

Remove binaryen0xb

---

src/build.py

Also, upload this file as lkgr/latest rather than creating
seperate local lkgr and latest files.

Add build_info.json to archived binary package

---

src/build.py

Not sure if this is useful to anyone else, but here's a quick way to query the status of all the things.

Add flag to show git statuses

---

src/build.py

Otherwise the three different builders will race to
update these files.
Also, add .json file extension so it clear what type
of file these are.
Also, and missing newline to end of json file.

Upload lkgr/latest file to per-builder sub-directory

---

src/test/d8_known_gcc_test_failures.txt

These tests failed after 0xc but pass now

Update d8 known failures

---

debian/README.Debian
src/emcc_wrapper.sh

Also, document behaviour in debian package README
file.

Honor EMCC_WASM_BACKEND in emcc wrapper scripts

---

src/testing.py

Fallback if rlimit doesn't exist (as it doesn't on windows).

---

src/build.py

Set WABT git remote to updated chromium mirror

---

src/build.py

Run with shell=True for git + gclient on windows.

---

src/build.py

Goes with https://github.com/WebAssembly/spec/pull/362

Update directory location of spec interpreter

---

src/build.py

Depends on https://github.com/WebAssembly/binaryen/pull/798

Use CMake install for Binaryen instead of manual script

---

src/build.py

Don't print anything when not syncing anything
Don't collect and write/print repo info when not a buildbot

Make script output quieter when not on a buildbot

---

debian/postinst
debian/prerm
src/build.py
src/emcc_wrapper.sh

Fix debian package wrapper scripts

---

src/test/d8_known_gcc_test_failures.txt
src/test/d8_musl_known_gcc_test_failures.txt

Update expected failures for bare d8 tests

---

src/host_toolchains.py

Its parameters changed in
https://chromium.googlesource.com/chromium/src/build/+/8a0a5a27d407a7bfa3c2360d9ea1e9c78838c892

Update invocation of setup_toolchain.py for win bot

---

src/build.py
src/host_toolchains.py

Refactor to remove duplication; NFC

Move goma-handling code into function in host_toolchains

---

src/build.py

Just like the other LLVM and the JS engines

Build fastcomp with goma/ccache

---

src/build.py
src/host_toolchains.py

This is the first step in using lld to link wasm object
files.

Checkout and build lld

---

src/build.py

Temporary measure until wasm support in lld is upstream

Build lld from sbc's branch

---

src/assemble_files.py
src/compile_torture_tests.py
src/execute_files.py
src/link_assembly_files.py
src/testing.py

Pass extras to outname_ctor 

---

src/test/run_known_gcc_test_failures.txt

LLVM change http://llvm.org/viewvc/llvm-project?view=revision&revision=306060 fixed these FastISel regressions

Remove FastISel expected failures

---

src/build.py

The copy of cygwin has been removed from V8, so we need something
to run bash and sed for generating some musl headers. The 'git bash'
hack we use for LLVM tests stil doesn't work for this, so bring back
our package of gnuwin32 tools. This essentially reverts rev 2f160b0
and uses it for musl instead of LLVM.

Bring back gnuwin32 tools for preparing musl sources on Windows

---

src/test/run_known_gcc_test_failures.txt

See:
https://github.com/WebAssembly/lld/commit/b5e5931adccf073e4af2a0df968cfaff4675333a

Update lld expectations now that we always write an empty table

---

src/test/run_known_gcc_test_failures.txt

See: https://github.com/WebAssembly/lld/pull/3

Update expectations in reponse to stack alignment fix in lld

---

src/test/run_known_gcc_test_failures.txt

Remove one other expected failure after stack size reduction

---

src/test/lld_known_gcc_test_failures.txt
src/test/lld_musl_known_gcc_test_failures.txt

Update lld expectations temporarily to make the waterfall green again,
until @sbc100 is back from vacation.

Update lld expectations temporarily

---

src/test/lld_known_gcc_test_failures.txt
src/test/lld_musl_known_gcc_test_failures.txt

Add missing .o in lld expectations

---

src/file_util.py
src/proc.py

- I accidentally deleted a line in #247. :( Restored it.
- Cosmetic change in `file_util.py` (NFC)

Bugfix in proc.check_call introduced by #247

---

src/test/lld_known_gcc_test_failures.txt
src/test/lld_musl_known_gcc_test_failures.txt

These should be fixed once we land https://reviews.llvm.org/D39107

Add expected failure for another test with zero sized symbol

---

src/build.py

This command accidentally changed is the previous commit

Fix v8 test comment

---

src/test/lld_known_gcc_test_failures.txt
src/test/run_known_gcc_test_failures.txt

https://github.com/jfbastien/musl/commit/f7a3ac80ec

Update expectations after recent musl change

---

src/test/run_known_gcc_test_failures.txt

https://github.com/jfbastien/musl/pull/20

Update expectations after musl change

---

src/test/lld_known_gcc_test_failures.txt

See: https://github.com/WebAssembly/lld/issues/12

Update expectations after lld fix

---

src/test/run_known_gcc_test_failures.txt

See: https://github.com/jfbastien/musl/pull/26

Update expectation after musl change

---

src/build.py
src/wasm_standalone.cmake

Also now respects the user's CMAKE_C_FLAGS.

Update CMake toolchain file to avoid spurious warnings

---

src/compile_torture_tests.py

See https://reviews.llvm.org/rL323220

Update target when building .s files since the default changed

---

src/assemble_files.py
src/link_assembly_files.py

The execute phase already has this improved handling

Better handling of glob not matching

---

src/test/asm2wasm_compile_known_gcc_test_failures.txt
src/test/run_known_gcc_test_failures.txt

Most likely cuases by fastcomp llvm 4.0 update

Update asm2wasm expectation

---

src/test/lld_known_gcc_test_failures.txt

Update lld known failures

---

src/build.py

Also switch to testing the lld version of the bare tests, since that's the way forward.

Run JSC tests using jsvu's JSC

---

src/host_toolchains.py

https://chromium-review.googlesource.com/c/chromium/src/+/980392
added some command line flags.

Update host_toolchain.py invocation

---

src/build.py

Possibly just speaking for myself, but I only ever skip asm2wasm by accident, and doing so can mess up my local config.
Also this simplifies code? So that's nice.

Always build the asm2wasm Emscripten config

---

src/build.py

warn_only for now, but get some sort of automated coverage working

Run Emscripten testsuite with LLD enabled

---

src/build.py

To match https://github.com/kripken/emscripten/pull/6697

LLD is now the default to invert the environment settings

---

src/build.py

Remove the O_NONBLOCK flag from the stdout fd. Taken from a link in a comment on crbug.com/829034

Try a fix for mac builder

---

src/build.py

This seems to more accurately reflect what this function is doing

Rename CompileLLVMTortureBinaryen -> CompileLLVMTortureEmscripten

---

src/build.py
src/test/lld_nostdlib_known_gcc_test_failures.txt
src/testing.py

This path wasn't being tested it seemed so had accumulated
some bugs.

Improve output of test execution when no know failures file is provided

---

luci-milo.cfg

Rename WASM console to Toolchain

---

cr-buildbucket.cfg

Use specific OS versions to prevent random failures

---

src/build.py

Tested with --test-include=emtest

Run wasmobj2 emscripten tests as well as binaryen2

---

src/build.py

The bare Windows binary used previously didn't support WebAssembly. That's now required in order to build struct_info.json for the wasm backend (since that configuration can't build asmjs).

Update node version to 8.12.0 and switch to windows zip package

---

src/build.py
src/test/run_known_gcc_test_failures.txt

Reverts WebAssembly/waterfall#411

Revert "Add torture XFails on Windows"

---

src/build.py
src/testing.py

This reverts commit f060c16cfd6d1fa128d60af551f2885f6aa2f7ea.

Revert "Use print instead of sys.stdout.write in testing.py (#435)"

---

src/build.py

Instead of explicit no_win/no_mac etc, use the existing filter mechanism.
This will make it easier to update the exclusions.

Use Filter mechanism for excluding OSes from steps

---

src/parallel_runner.py
src/testing.py

Add missing newline.
Be little more explicit when printing periodic status.

Cleanup test runner stdout

---

src/test/run_known_gcc_test_failures.txt

I assume these new successes are due to https://reviews.llvm.org/D58656

Update test expectations after llvm change

---

src/build.py

At least until we can update the bots.
(Temporary) Fix for #467

Define LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN in llvm build

---

.gitignore
src/build.py
src/work_dirs.py

In preparation for making this script runnable from new bot infrastructure, stop hard-coding the working directories.

Add work_dirs.py to allow overriding the working directories

---

src/build.py

This is an attempt to diagnose the issue we are seeing on the bots
with modified config.sub/config.guess files.

Temporarily disable emscripten testing

---

src/build.py

It's the latest LTS, and should work properly with JSVU.

Update nodeJS to 10.15.3

---

src/build.py

To see if that is the root cause of the waterfall failures.

Trial removal of parallelism from wasi sysroot build

---

src/build.py
src/wasi.js

With a recent wasi-sysroot change we now need a working `environ_get`
so implement that along with some other improvements.
See https://github.com/CraneStation/wasi-sysroot/commit/07858345bc489ad633054e36061979ebc1624424

Implement more of wasi_unstable API in wasi.js

---

src/build.py

See https://bugs.chromium.org/p/chromium/issues/detail?id=940663

Capture stdout/stderr from make in attempt to work around infra issue

---

src/buildbot.py
src/cloud.py

Allow detecting if we are the emscripten-releases bot, and upload to the proper bucket based on that.

Prepare for emscripten-releases uploads

---

src/build.py

depot_tools and the recipe handles that.

Don't clobber sync dirs when in emscripten-releases run

---

src/test/run_known_gcc_test_failures.txt
src/wasi.js

We now have a lot more filesystem support as well as support
argv and environ.

Implement more of the WASI syscalls interface in wasi.js

---

src/buildbot.py

The archives are no longer used for any purpose.

Don't upload from the waterfall bots anymore.

---

src/build.py

This repo was renamed upstream

Rename wasi-sysroot -> wasi-libc

---

src/build.py

This seems to work locally, but not sure it will work on the bots.
So far just libc, to start with.
See emscripten-core/emscripten#8795 for background discussion

Start to package emscripten libraries in the zips

---

src/build.py

See https://github.com/emscripten-core/emscripten/issues/5418

Fix llvm build on older (10.12 and below) OSX versions

---

src/test/run_known_gcc_test_failures.txt

See https://reviews.llvm.org/D66359

Update expectations after llvm vaarg fix

---

src/execute_files.py
src/wasi.js

This is the version now implemented in wasi-libc@master.

Update wasi.js to implement latest wasi version:  wasi_snapshot_preview1

---

src/build.py

Python scripts executed by gn don't work under python3, so use vpython
to isolate them from build.py's environment. This requires invoking
gn directly rather than using V8's gn scripts.

Use vpython as gn's script interpreter

---

src/build.py

This fixes the wabt build that now depends on submodules

Git clone and check including submodules

---

src/build.py

Also, attempt to debug "can't find node" issue in emscripten-releases
builder:
https://ci.chromium.org/p/emscripten-releases/builders/try/linux/b8890072294421298416

Attempt to debug node path issues

---

src/build.py

See https://github.com/emscripten-core/emscripten/issues/10294

Use `npm ci` over npm install

---

src/test/run_known_gcc_test_failures.txt

I guess the llvm-change that caused this fixed or reverted.

Revert updated expectations from #625

---

.travis.yml
__init__.py
src/__init__.py
src/build.py
src/buildbot.py
src/cloud.py
src/compile_torture_tests.py
src/execute_files.py
src/file_util.py
src/host_toolchains.py
src/link_assembly_files.py
src/parallel_runner.py
src/proc.py
src/testing.py

Remove support for python2

---

src/build.py

I believe this issue was fixed in:
https://github.com/emscripten-core/emscripten/pull/9347

Remove now unnecessary hack

---

src/build.py

Add a clobber

---

src/build.py

See https://github.com/emscripten-core/emscripten/pull/11126

Support new default emscripten cache directory

---

src/build.py

Goes with WebAssembly/wabt#1435

Disable libwasm in wabt build

---

src/compile_torture_tests.py
src/link_assembly_files.py
src/test/lld_known_gcc_test_failures.txt

See https://github.com/WebAssembly/wasi-libc/pull/183

Update expectations after wasi-libc added signal emulation

---

src/build.py

This creates a symlink to the XCode SDK sysroot under /Library.
The symlink is located in the build root. This change allows the
build to use a relative sysroot path.

Set relative symlink to XCode SDK sysroot on Mac

---

src/build.py

See https://github.com/emscripten-core/emscripten/pull/12131

Remove native optimizer build

---

cr-buildbucket.cfg

Prepare mac bot upgrade

---

src/build.py
src/host_toolchains.py
src/testing.py

This fixes what looks like an actual bug in make_blocking

Remove some unused args

---

.github/workflows/build.yml
src/build.py
src/create_sysroot.sh

Landing initially with debian/sarge which means nothing
should change/break.  The plan being to update to something
with a more recent libc++.

Use custom sysroot creator to build our linux sysroot

---

src/build.py
src/create_sysroot.sh

Add zlib to sysroot

---

src/build.py
src/create_sysroot.sh

This is enough to allow C++-17 to be used in he binaryen build.

Switch sysroot to ubuntu bionic

---

src/build.py

Try to help with https://github.com/emscripten-core/emscripten/pull/13418 , see discussion there

Clobber the build

---

src/build.py

Fixes https://github.com/emscripten-core/emsdk/issues/720

Add llvm-dwp to list of installed tools
